name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install -r requirements.txt  # Adjust this based on your project structure

    - name: Run script
      run: python PolygonAperture.py  # Replace with the actual name of your script

